workflows:
  default:
    name: BossCash
    max_build_duration: 10
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Crear Base de Android
        script: |
          flutter create . --platforms=android --overwrite
      - name: Inyectar Calculadora Real
        script: |
          rm -f lib/main.dart
          curl -o lib/main.dart https://raw.githubusercontent.com/${CM_REPO_SLUG}/${CM_COMMIT}/lib/main.dart
      - name: Compilar APK Real
        script: |
          flutter build apk --release
    artifacts:
      - build/**/*.apk
